#!/usr/bin/env python3
"""Configure VPS for GetLeveraged Trading Accounts"""

import paramiko
import time
import sys
from credential_manager import get_vps_credentials, get_credentials, CredentialError

# VPS Configuration - loaded from credential_manager
try:
    _vps_creds = get_vps_credentials("VPS_1")
    VPS_HOST = _vps_creds["host"]
    VPS_USER = _vps_creds["user"]
    VPS_PASS = _vps_creds["password"]

    # Get MT5 credentials
    _gl1 = get_credentials("GL_1")
    _gl2 = get_credentials("GL_2")
    _gl3 = get_credentials("GL_3")
    _atlas = get_credentials("ATLAS")
except CredentialError as e:
    print(f"ERROR: {e}")
    sys.exit(1)

# GetLeveraged Accounts - passwords loaded from credential_manager
ACCOUNTS = {
    "getleveraged_1": {
        "login": str(_gl1["account"]),
        "password": _gl1["password"],
        "server": _gl1["server"]
    },
    "getleveraged_2": {
        "login": str(_gl2["account"]),
        "password": _gl2["password"],
        "server": _gl2["server"]
    },
    "getleveraged_3": {
        "login": str(_gl3["account"]),
        "password": _gl3["password"],
        "server": _gl3["server"]
    }
}

# Atlas Account - password loaded from credential_manager
ATLAS_ACCOUNT = {
    "login": str(_atlas["account"]),
    "password": _atlas["password"],
    "server": _atlas["server"]
}

def execute_command(ssh, command, timeout=30):
    """Execute a command on the VPS and return output"""
    stdin, stdout, stderr = ssh.exec_command(command, timeout=timeout)
    output = stdout.read().decode('utf-8')
    error = stderr.read().decode('utf-8')
    exit_code = stdout.channel.recv_exit_status()
    return output, error, exit_code

def main():
    print("=" * 60)
    print("VPS GetLeveraged Account Configuration")
    print("=" * 60)

    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())

    try:
        print(f"\nConnecting to VPS {VPS_HOST}...")
        ssh.connect(VPS_HOST, username=VPS_USER, password=VPS_PASS, timeout=30)
        print("Connected!")

        # Step 1: Backup current .env
        print("\n[Step 1] Backing up current configuration...")
        output, error, code = execute_command(ssh, "cp /root/.env /root/.env.backup.$(date +%Y%m%d_%H%M%S)")
        print("Backup created.")

        # Step 2: Check if signal generator is running
        print("\n[Step 2] Checking running services...")
        output, error, code = execute_command(ssh, "ps aux | grep etare_signal_generator | grep -v grep")
        if output.strip():
            print("Signal generator is running:")
            print(output)

        # Step 3: Create multi-account configuration file
        print("\n[Step 3] Creating multi-account configuration...")

        accounts_config = f'''# ETARE Multi-Account Configuration
# Generated by VPS Configuration Script

import json

TRADING_ACCOUNTS = {{
    "getleveraged_1": {{
        "login": {_gl1["account"]},
        "password": "{_gl1["password"]}",
        "server": "{_gl1["server"]}",
        "enabled": True,
        "risk_percent": 1.0,
        "max_positions": 3
    }},
    "getleveraged_2": {{
        "login": {_gl2["account"]},
        "password": "{_gl2["password"]}",
        "server": "{_gl2["server"]}",
        "enabled": True,
        "risk_percent": 1.0,
        "max_positions": 3
    }},
    "getleveraged_3": {{
        "login": {_gl3["account"]},
        "password": "{_gl3["password"]}",
        "server": "{_gl3["server"]}",
        "enabled": True,
        "risk_percent": 1.0,
        "max_positions": 3
    }},
    "atlas_main": {{
        "login": {_atlas["account"]},
        "password": "{_atlas["password"]}",
        "server": "{_atlas["server"]}",
        "enabled": False,  # Enable when ready
        "risk_percent": 1.0,
        "max_positions": 3
    }}
}}

# Primary account for single-account mode
PRIMARY_ACCOUNT = "getleveraged_1"

def get_account(name=None):
    """Get account configuration by name or primary"""
    if name is None:
        name = PRIMARY_ACCOUNT
    return TRADING_ACCOUNTS.get(name)

def get_enabled_accounts():
    """Get all enabled accounts"""
    return {{k: v for k, v in TRADING_ACCOUNTS.items() if v.get("enabled", False)}}
'''

        # Write accounts config file
        cmd = f'''cat > /root/QuantumTradingLibrary/accounts_config.py << 'EOFCONFIG'
{accounts_config}
EOFCONFIG'''
        output, error, code = execute_command(ssh, cmd)
        if code == 0:
            print("Multi-account config created at /root/QuantumTradingLibrary/accounts_config.py")
        else:
            print(f"Error creating config: {error}")

        # Step 4: Update .env for primary GetLeveraged account
        print("\n[Step 4] Updating .env with primary GetLeveraged account...")

        new_env = f'''# MT5 Connection Credentials
# Primary: GetLeveraged Account {_gl1["account"]}
MT5_LOGIN={_gl1["account"]}
MT5_PASSWORD={_gl1["password"]}
MT5_SERVER={_gl1["server"]}

# Bridge Security
MT5_BRIDGE_API_KEY=etare-secure-bridge-2026

# Logging
LOG_LEVEL=INFO

# Multi-Account Mode (set to true for round-robin trading)
MULTI_ACCOUNT_MODE=false
'''

        cmd = f'''cat > /root/.env << 'EOFENV'
{new_env}
EOFENV'''
        output, error, code = execute_command(ssh, cmd)
        if code == 0:
            print(f"Updated .env with GetLeveraged account {_gl1['account']}")
        else:
            print(f"Error updating .env: {error}")

        # Step 5: Verify the new configuration
        print("\n[Step 5] Verifying new configuration...")
        output, error, code = execute_command(ssh, "cat /root/.env")
        print("New .env contents:")
        print(output)

        # Step 6: Check if MT5 terminal config needs updating
        print("\n[Step 6] Checking MT5 terminal configuration...")
        output, error, code = execute_command(ssh, "ls -la /root/.wine_mt5/drive_c/Program\\ Files/MetaTrader\\ 5/")
        print(output)

        # Look for server files
        output, error, code = execute_command(ssh, "find /root/.wine_mt5 -name '*.srv' 2>/dev/null | head -10")
        if output.strip():
            print("\nFound server files:")
            print(output)

        # Step 7: Check for GetLeveraged server file
        print("\n[Step 7] Checking for GetLeveraged server configuration...")
        output, error, code = execute_command(ssh, "find /root/.wine_mt5 -name '*GetLeveraged*' -o -name '*getleveraged*' 2>/dev/null")
        if output.strip():
            print("Found GetLeveraged files:")
            print(output)
        else:
            print("GetLeveraged server files not found - may need to add server")

        print("\n" + "=" * 60)
        print("Configuration Complete!")
        print("=" * 60)
        print("""
Next Steps:
1. Restart the signal generator with:
   systemctl restart etare-signal-generator (if systemd service exists)
   OR kill and restart the python process

2. The MT5 terminal may need to be configured to connect to GetLeveraged-Trade server
   - The server files might need to be downloaded from GetLeveraged broker

3. Monitor logs for successful connection:
   tail -f /root/QuantumTradingLibrary/06_Integration/HybridBridge/*.log
""")

        ssh.close()
        print("\nConnection closed.")

    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()
